# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 15:12
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=select_multiple_field.models.SelectMultipleField(choices=[('a', 'Aspigirl'), ('c', 'Programming')], default='a', max_length=10),
        ),
    ]
